### ISSUE TITLE
Create a distroless image of schema-registry

### ISSUE THREAD

**Issue by adriancole** [hypertrace/schema-registry#5]
Right now, our schema-registry image uses a different base image, which is also not our base java image. It seems that schema-registry, while a java process, follows some conventions that places things in different parts of the file system based on yum packages

https://github.com/confluentinc/schema-registry-images

This complicates, but doesn't make impossible rebasing over a distroless image.

cc @jeqo @ravisingal

**Comment by adriancole** [comment]
also raised an issue upstream https://github.com/confluentinc/schema-registry-images/issues/29

**Comment by JBAhire** [comment]
Schema registry dependency is removed with hypertrace/hypertrace#75
